# Generated by Django 4.1.4 on 2022-12-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expired_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_fee_amount', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'expired_payment',
            },
        ),
    ]
