# Generated by Django 4.1.4 on 2022-12-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expired_payments', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expired_payment',
            name='payment_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment_user'),
        ),
    ]
